---
- block:
  - name: install compiling dependency packages
    apt: "name={{ item }} state=latest"
    with_items:
      - build-essential
      - libreadline-dev
      - libssl-dev
      - libncurses5-dev
      - zlib1g-dev
  - name: delete old softether package if exists
    script: remove_softether.sh
  - name: delete if dest dir exists
    file:
      path: "/tmp/SoftEtherVPN-master"
      state: "absent"
  - name: download softether latest source code
    unarchive:
      src: "https://github.com/SoftEtherVPN/SoftEtherVPN/archive/master.zip"
      dest: "/tmp"
      remote_src: "yes"
  - name: compiling softether vpn
    shell: "./configure && make && make install"
    args:
      chdir: "/tmp/SoftEtherVPN-master"
  - name: setup systemd unit
    copy:
      src: "softether.service"
      dest: "/etc/systemd/system/softether.service"
      owner: "root"
      group: "root"
      mode: "0644"
  - name: reload systemd config
    command: "systemctl daemon-reload"
  - name: (re)start softether vpn server
    service: "name=softether state=restarted enabled=yes"
  tags:
    - softether
