---
- block:
  - name: install compiling dependency packages
    ansible.builtin.apt: "name={{ packages }} state=latest"
    vars:
      packages:
      - build-essential
      - libreadline-dev
      - libssl-dev
      - libncurses5-dev
      - zlib1g-dev
  - name: delete old softether package if exists
    ansible.builtin.script: remove_softether.sh
  - name: delete if dest dir exists
    ansible.builtin.file:
      path: "/tmp/SoftEtherVPN-master"
      state: "absent"
  - name: download softether latest source code
    ansible.builtin.unarchive:
      src: "https://github.com/SoftEtherVPN/SoftEtherVPN/archive/master.zip"
      dest: "/tmp"
      remote_src: "yes"
  - name: compiling softether vpn
    ansible.builtin.shell: "./configure && make && make install"
    args:
      chdir: "/tmp/SoftEtherVPN-master"
  - name: setup systemd unit
    ansible.builtin.copy:
      src: "softether.service"
      dest: "/etc/systemd/system/softether.service"
      owner: "root"
      group: "root"
      mode: "0644"
  - name: reload systemd config
    ansible.builtin.command: "systemctl daemon-reload"
  - name: (re)start softether vpn server
    ansible.builtin.service: "name=softether state=restarted enabled=yes"
  tags:
    - softether
